apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: app-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: sursubra/python-app:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: "REPLACE_VERSION"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: app-deployment
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
